name: Deploy Azure Infrastructure

on:
  push:
    branches: [ main ]
    paths: 
      - '**/*.bicep'
      - '.github/workflows/deploy-infrastructure.yml'
  workflow_dispatch:

env:
  RESOURCE_GROUP: Online-cornerRG
  LOCATION: eastus
  SQL_RESOURCE_GROUP: OnlineCornerSQL-RG
  SQL_LOCATION: southafricanorth
  DNS_PREFIX: onlinecorner
  ACR_NAME: ocorneracr3
  DEPLOYMENT_NAME: deploy-infra-${{ github.run_number }}
  SQL_DEPLOYMENT_NAME: deploy-sql-${{ github.run_number }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Azure CLI and Bicep
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az bicep install
        az bicep upgrade

    - name: Validate Bicep templates
      run: |
        az bicep build --file ./main.bicep
        az bicep build --file ./sql.bicep

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Ensure Main Resource Group Exists
      run: |
        az group show --name ${{ env.RESOURCE_GROUP }} || \
        az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }}

    - name: Deploy Main Infrastructure
      id: deploy_main
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: ./main.bicep
        parameters: acrName=${{ env.ACR_NAME }}
        deploymentName: "${{ env.DEPLOYMENT_NAME }}"
        failOnStdErr: false

    - name: Ensure SQL Resource Group Exists
      run: |
        az group show --name ${{ env.SQL_RESOURCE_GROUP }} || \
        az group create --name ${{ env.SQL_RESOURCE_GROUP }} --location ${{ env.SQL_LOCATION }}

    - name: Deploy SQL Server and Database
      id: deploy_sql
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.SQL_RESOURCE_GROUP }}
        template: ./sql.bicep
        parameters: |
          sqlAdminPassword=${{ secrets.SQL_ADMIN_PASSWORD }}
          location=${{ env.SQL_LOCATION }}
        deploymentName: "${{ env.SQL_DEPLOYMENT_NAME }}"
        failOnStdErr: false

    - name: Extract Outputs from Main Deployment
      id: get_outputs
      run: |
        outputs=$(az deployment group show \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name "${{ env.DEPLOYMENT_NAME }}" \
          --query properties.outputs)

        echo "controlPlaneFQDN=$(echo $outputs | jq -r '.controlPlaneFQDN.value // empty')" >> $GITHUB_ENV
        echo "aksClusterName=$(echo $outputs | jq -r '.aksClusterName.value // empty')" >> $GITHUB_ENV
        echo "acrName=$(echo $outputs | jq -r '.acrName.value // empty')" >> $GITHUB_ENV
        echo "appGatewayPublicIp=$(echo $outputs | jq -r '.appGatewayPublicIp.value // empty')" >> $GITHUB_ENV
        echo "webAppUrl=$(echo $outputs | jq -r '.webAppUrl.value // empty')" >> $GITHUB_ENV

    - name: Output Infra Deployment Info
      run: |
        echo "✅ AKS Cluster Name: $aksClusterName"
        echo "✅ AKS Control Plane FQDN: $controlPlaneFQDN"
        echo "✅ ACR Name: $acrName"
        echo "✅ App Gateway Public IP: $appGatewayPublicIp"
        echo "✅ Web App URL: $webAppUrl"
